name: secure_random
description: Secure random generator
version: 1.0.0
author: "Ming Chen <ming_c@hotmail.com>"
homepage: https://github.com/mingchen/secure_random

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:


dev_dependencies:
  test: ^1.3.0